version: '3.8'

services:
  # Chạy server Backend API
  backend:
    build: .
    image: douyin-app-image:latest
    container_name: douyin_backend
    restart: always
    ports:
      - "8000:8000"
    command: ["python", "run_backend.py"]
    environment:
      - HEADLESS=true
      - WHISPER_MODEL=base
    volumes:
      - ./config:/app/config
      - ./database:/app/database
      - ./.env:/app/.env
      - ./backend:/app/backend
      - ./auth_client.py:/app/auth_client.py
      - ./run_backend.py:/app/run_backend.py

  # Chạy Tool Auto Crawl & Upload ngầm 24/7
  worker:
    image: douyin-app-image:latest
    container_name: douyin_worker
    restart: always
    command: ["python", "main.py", "auto", "--file", "urls.txt"]
    environment:
      - HEADLESS=true
      - WHISPER_MODEL=base
    volumes:
      - ./config:/app/config
      - ./database:/app/database
      - ./.env:/app/.env
      - ./music:/app/music
      - ./logs:/app/logs
      - ./downloads:/app/downloads
      - ./processed:/app/processed
      - ./urls.txt:/app/urls.txt
      - ./processor:/app/processor
      - ./crawler:/app/crawler
      - ./uploader:/app/uploader
      - ./utils:/app/utils
      - ./scheduler:/app/scheduler
      - ./main.py:/app/main.py
      - ./auth_client.py:/app/auth_client.py
